import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Providers from "../components/ui/utility/providers";
import React from "react";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

import { cn } from "@/lib/utils"

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("bg-background font-sans antialiased", fontSans.variable)}>
				<Providers>
					<NavBar />
					<div className="min-h-screen">
						{children}
					</div>
				</Providers>
				<Footer />
			</body>
		</html>
	);
}
