import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Providers from "../app/ui/utility/providers";
import React from "react";
import NavBar from "@/app/components/navbar";
import Footer from "@/app/components/footer";

import { cn } from "@/lib/utils"

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased",fontSans.variable)}>
				<Providers>
					<NavBar />
					<div className="">
						{children}
					</div>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
